# Generated by Django 3.0.2 on 2020-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_c', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
