# Generated by Django 3.0.2 on 2020-01-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_c', '0003_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='user',
        ),
    ]
