# Generated by Django 3.0.2 on 2020-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_c', '0004_auto_20200109_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='O',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
                ('academy', models.CharField(max_length=40)),
                ('tname', models.CharField(max_length=20)),
                ('tid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('sid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('tid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
