# Generated by Django 3.0.2 on 2020-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_c', '0006_auto_20200109_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='e',
            name='cname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='e',
            name='sname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='e',
            name='tname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
