# Generated by Django 3.0.2 on 2020-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_c', '0007_auto_20200112_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='o',
            name='normal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='o',
            name='test',
            field=models.FloatField(default=0),
        ),
    ]
